version: '3'
services:
  ibmmq:
    #build:
    #  dockerfile: Dockerfile-mq
    image: "ibmcom/mq"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - 1414:1414
      - 9443:9443
  web:
    build:
      dockerfile: Dockerfile-web
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - ibmmq

